blank_issues_enabled: true
contact_links:
  - name: ğŸ“š Search for documentation
    url: https://docs.srnyx.xyz
    about: "In the wiki you can find an explanation how to set up the templates properly."
  - name: ğŸ’¬ Get help
    url: https://srnyx.xyz/discord
    about: "If you need help setting up the templates or have a question please join the Discord server and do so in the #support channel."
  - name: ğŸ’¡ Suggest your idea(s)
    url: https://srnyx.xyz/discord
    about: "If you have any ideas or feedback please join the Discord server and do so in the #suggestions channel."
  - name: â­ Leave a review
    url: https://srnyx.xyz/review
    about: "If you enjoy my work and these templates, consider leaving a review!"