blank_issues_enabled: true
contact_links:
  - name: ğŸ’¬ Support
    url: https://srnyx.com/discord
    about: "If you need help with the template or have a question, please join the Discord server and ask there."
  - name: â­ Leave a review
    url: https://srnyx.com/review
    about: "If you enjoy my work and these templates, consider leaving a review!"
